language: python
python:
  - "2.7"

# safelist
branches:
  only:
  - 17.1.4
  - 17.1.5
  - 17.1.6
  - 17.2.1
  - 17.2.2
  - 17.2.3
  - 17.2.4
  - 17.2.5
  - AV-32567-CASSETTE

# command to install dependencies
install:
- pip install pytest pyyaml requests pyparsing paramiko avisdk pycrypto ecdsa pyOpenssl nose-html-reporting nose-testconfig ConfigParser xlsxwriter jinja2 pandas openpyxl appdirs pexpect xlrd unittest2 networkx vcrpy betamax
- export PYTHONPATH=$PWD/python/
- echo $PYTHONPATH


# command to execute unit tests
script:
- pytest ./python/avi/sdk/test/test_avi_api.py -vvvv  --config ./python/avi/sdk/test/test_api.cfg --color=yes
